FROM ghcr.io/foundry-rs/foundry:latest

ARG PORT
ENV PORT=${PORT}
ARG MNEMONIC
ENV MNEMONIC=${MNEMONIC}
ARG FORK_URL
ENV FORK_URL=${FORK_URL}
EXPOSE $PORT

ENTRYPOINT anvil --host 0.0.0.0 -m "$MNEMONIC" -p $PORT --fork-url $FORK_URL --no-cors
